services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/code/app/
    entrypoint:
      bash -c "sleep 5 &&
               alembic upgrade head &&
               uvicorn app.main:create_app --host 0.0.0.0 --port 8000"
    restart: always
    env_file:
      - .env

  test:
    build: .
    depends_on:
      - db
    env_file:
      - .test.env
    command: pytest -s

  db:
    container_name: "db"
    image: postgres:15.6-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"